server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    ddl-auto: create

application-version: 1.0
